tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/core"
tap "microsoft/git"
tap "koekeishiya/formulae"

# Terminal Tool
brew "duckdb"
brew "jq"
brew "openssl@3", link: false
brew "fastfetch"
brew "wget"
brew "ripgrep"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
brew "jordanbaird-ice"
brew "lazygit"
brew "bat"

# Cask
cask "karabiner-elements"
cask "cursor"
cask "hammerspoon"
cask "ubersicht"
cask "git-credential-manager-core"
cask "1password"
cask "raycast"
cask "slack"
cask "spotify"
cask "arc"
cask "google-chrome"
cask "monitorcontrol"
cask "cloudflare-warp"
cask "evkey"
